# This is the basic info about your site. Definitely change this.
title: Knih
author: chamik
author_realname: Jakub Hampl
type: Person

description: Krátké úvahy a recenze knih

url: "https://knih.chamik.eu" # the base hostname & protocol for your site, e.g. https://example.com
timezone: Europe/Prague

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss

# Unless you know what are you doing, you probably don't want to change anything below this line

postcss:
  cache: false

permalink: pretty

source: src/

exclude: [
  .gitignore,
  styles/index.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  tailwind.config.js,
  README.md,
  build/,
]
